version: '3.3'
services:
    web:
        image: nginx:alpine
        depends_on:
            - db
            - phpmyadmin
        volumes:
            - './nginx/nginx.conf:/etc/nginx/nginx.conf'
            - './php:/var/www/html/'
        ports:
            - '9876:80'
            - '9877:81'
        restart: always

    db:
        container_name: mysqltcy
        image: mysql
        command: '--default-authentication-plugin=mysql_native_password'
        environment:
            MYSQL_ROOT_PASSWORD: 12345
            MYSQL_ROOR_USER: ruser
            MYSQL_DATABASE: db
            MYSQL_USER: user
            MYSQL_PASSWORD: 12345

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: my-php-admin
        ports:
            - '5400:1130'
        restart: always
        environment:
            PMA_HOST: mysqltcy
    php:
        build: 
          context: ./
        volumes:
            - './php:/var/www/html/'
        restart: always

